---
name: Catalyst-Plugin-Authentication-Credential-CHAP
version: 0.02
author:
  - 'Renaud Drousies <rdrousies@cpan.org>'
abstract: |-
  Authenticate a user
  using a CHAP login system.
license: perl
build_requires:
  Catalyst: '>= 5.65'
  Catalyst::Plugin::Authentication::Credential::Password: 0
  Catalyst::Plugin::Session: 0
  Digest: 0
  Test::More: 0
provides:
  Catalyst::Plugin::Authentication::Credential::CHAP:
    file: lib/Catalyst/Plugin/Authentication/Credential/CHAP.pm
    version: 0.02
generated_by: Module::Build version 0.2612
